### ISSUE TITLE
proc_close() fails cause errors.

### ISSUE THREAD

**Issue by feanorknd** [OOPS-ORG-PHP/mod_execdir#22]
Hello:

First of all, thanks so much for your efforts at building up this perfectly useful extension... Highly appreciated.

I have errors along with my config:

- php 7.1 FPM

- php config maybe related: disable_functions: exec,passthru,shell_exec,system,show_source,popen,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals

- opcache on.

- mod_execdir built up and configured as dynamic extension for php.

- We are using "wkhtmltopdf" to build up pdfs.

- Also "/vendor/mikehaertl/phpwkhtmltopdf" libraries to call it and execute from PHP.

Problem is:
- First execution, pdf is generated and downloaded perfectly... feels like if there is no problem at all.
- Following executions always give error:

```html
<b>Fatal error</b>:  Uncaught Error: Call to undefined function mikehaertl\shellcommand\proc_close() in /home/xxxxxxxxx/public_html/vendor/mikehaertl/php-shellcommand/src/Command.php:322
Stack trace:
#0 /home/xxxxxxxxx/public_html/vendor/mikehaertl/phpwkhtmltopdf/src/Pdf.php(270): mikehaertl\shellcommand\Command-&gt;execute()
#1 /home/xxxxxxxxx/public_html/vendor/mikehaertl/phpwkhtmltopdf/src/Pdf.php(178): mikehaertl\wkhtmlto\Pdf-&gt;createPdf()
#2 /home/xxxxxxxxx/public_html/test.php(21): mikehaertl\wkhtmlto\Pdf-&gt;send()
#3 {main}
  thrown in <b>/home/xxxxxxxxx/public_html/vendor/mikehaertl/php-shellcommand/src/Command.php</b> on line <b>322</b><br />
```

Then some testing....

- if just current php thread process die, the next execution will run ok.
- if you try it and it creates a new php thread, the execution will be ok same way.
- if you reload or restart php, the php thread will be of course new, and the execution will be fine.

It just appears to cause error only when re-using a php-fpm existing thread.

Piece of code around the path /home/xxxxxxxxx/public_html/vendor/mikehaertl/php-shellcommand/src/Command.php:322 is:

```php
            $descriptors = array(
                1   => array('pipe','w'),
                2   => array('pipe', $this->getIsWindows() ? 'a' : 'w'),
            );
            $process = proc_open($command, $descriptors, $pipes, $this->procCwd, $this->procEnv, $this->procOptions);

            if (is_resource($process)) {

                $this->_stdOut = stream_get_contents($pipes[1]);
                $this->_stdErr = stream_get_contents($pipes[2]);
                fclose($pipes[1]);
                fclose($pipes[2]);

                $this->_exitCode = proc_close($process);

                if ($this->_exitCode!==0) {
                    $this->_error = $this->_stdErr ? $this->_stdErr : "Failed without error message: $command";
                    return false;
                }
            } else {
                $this->_error = "Could not run command $command";
                return false;
            }
```

The line causing error is:

` $this->_exitCode = proc_close($process);`

Uncaught Error: Call to undefined function mikehaertl\shellcommand\proc_close()

Well.....

If I disable, dynamic exec_dir extension, no problem appears at all... will be fine.

Thanks so much for your interest!

--

Gino

**Comment by feanorknd** [comment]
FIXED:

It was opcache related:

```diff
`47c47
< opcache.fast_shutdown=1
---
> opcache.fast_shutdown=0`
```

Just opcache.fast_shutdown=0 and no problem at all.

Thanks so much.
